### ISSUE TITLE
Decimal type serialization as strings

### ISSUE THREAD

**Issue by juaiglesias** [schmittjoh/serializer#1428]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

Hello everyone! 
We update to v3.18 and we are having problems with serializations of decimal types. We had to rollback to v3.17.x, I guess is related with https://github.com/schmittjoh/serializer/pull/1398, but i'm thinking this should maybe be something at least configurable.

**Comment by Legenyes** [comment]
We have same issue.

**Comment by fmarchalemisys** [comment]
I take it [patch #1398](https://github.com/schmittjoh/serializer/pull/1398) was applied because of [doctrine bug #5594](https://github.com/doctrine/orm/issues/5594).

Doctrine's unit of work strictly compares the decimal value fetched from the db (as a string) with the value stored in the entity. If the entity's value is somehow converted to a float, the comparison becomes `string !== float`. The unit of work detects a change and needlessly updates the db.

For instance, this code triggers the above bug every time:

````
#[ORM\Column(type: Types::DECIMAL, scale: 2)]
private float $amount = 0.0;
````

Therefore, I suspect the patch was necessary because a GET on a json payload containing a DECIMAL, followed by an UPDATE without changing anything in the payload, triggers an unnecessary db write due to the DECIMAL being converted to a float in the json payload.

In other words, the patch wants to avoid this issue: A decimal value is read as a string from the db. It is converted to a float in the json payload. The caller returns the payload without changing the float. The float is written back into the entity. The db gets updated because the decimal string is not strictly equal to the float.

Some doctrine developers argue that `decimal` is not equivalent to `float`. Therefore it is a feature, not a bug.

Considering how this "feature" affects others, it is indeed a full-fledged bug.

The serializer must not expose that technical detail to the client.

Moreover, returning the decimal value as a string is pointless. Most clients have to manipulate the value as a float. Either to do some computation or to format the value according to the user's locale. They have to deal with any numerical precision anyway.

**Comment by fishbone1** [comment]
This is a big problem for me. After a while we noticed all kinds of frontend problems. Values like money amounts or stock quantity  are calculated incorrectly: `"1" + "2" = "12"`.
Sort orders are wrong (12 > 2, but "12" < "2").

In general the string representation is a better solution (with or without doctrine), because there is also no decimal type in JSON itself and the float value is inaccurate. I wish it was this way when I started coding.

But now there could be thousands of cases like that in my application and I don't know how to find them quickly. I see a high risk for data damage and incosistencies. Wrong product prices etc would be a nightmare.

So I wonder if there is a quick workaround for restoring the old behavior. Is there a way to override the mapping? Is there a config option in the bundle (yes I know thats a separate project, but the issue is here)?

**Comment by naitsirch** [comment]
> Considering how this "feature" affects others, it is indeed a full-fledged bug.

I would not say it's a bug, but it's a huge backward compatibility break and should not go into a minor update.

@goetas Can you please have a look?

**Comment by goetas** [comment]
can someone provide a PR to fix this issue? as example allowing to opt in into one or the other behavior?

**Comment by fmarchalemisys** [comment]
In order to decide how to opt in/out of the feature, some questions need to be answered.

What's the rational for sending a number as a string in the first place? The PR says it's to make like doctrine but that tells nothing as far as the json payload and the consuming parties are concerned. What are the actual cases prompting for this change?

Is the proper fix not just to revert #1398 ?

Under what circumstances does a javascript developer want to manipulate a decimal number without ever converting it to a float? Does it help anyone if the number ends up as a string when the json payload is converted to a native object on the client side? In other words, can it be called an improvement if every javascript developer must call `parseFloat()` on every number before using it?

How can a php developer decide when the javascript developer needs a string instead of a float?

Can the php developer even make a safe/sane choice for anyone and any language consuming the serialized object?

**Comment by fishbone1** [comment]
Counter question: What makes you think that a float would be the appropriate representation for a decimal? Floats in Javascript have the same problems like in PHP. `parseFloat()` is also a bad idea. JS has `BigDecimal` for instance. However there is no support for it in the JSON format. So in general I think it is a better solution to use string instead of float. The latter is too inaccurate. At least string is safe enough that it will keep all information.

The problem I see here rather is the breaking change of the default behavior and the lack of an option (at least, as far as I know) to quickly change to the old behavior.

**Comment by fmarchalemisys** [comment]
@fishbone1 Json is not the problem. There is no loss of precision in json. Json travels as a text payload. Numerical inaccuracies come when json content is converted into a native object by the receiving party. 

If a javascript developer is worried about numerical inaccuracies in his code, he can use bignumber.js on the received (float) value as well as a string. The reverse is not true. If the value is a string, client side developers (javascript, java, python, php, etc) must all take one additional step to decode the string into a usable number, be it float or fixed.

My point is that it's not up to the php developer to assume consumers are inherently incapable of processing decimal numbers. Neither does he need to take action on their behalf. Let them tackle the problem as best they see fit.

From the receiving javascrit side's perspective, it pains me to have to post-process dozens or hundreds of json with `parseFloat()` or `new BigNumber()` knowing that if I forget even one conversion, I end up with hard to debug `"1"+"2"="12"` or `"12"<"2"`.

**Comment by goetas** [comment]
You can always override the default seialization mode declaring explicitly the more (`@Type("float")`)
