### ISSUE TITLE
Allow Constructed Object to be Passed to Deserialize

### ISSUE THREAD

**Issue by cmorelli** [schmittjoh/serializer#79]
It doesn't appear that there's a way to give an already constructed object to the deserialize method (in which case the serializer would just skip the object construction phase and begin mapping properties).

My use case is simple:
In a REST API, I want to allow a user to create or update objects. Each type of operation (create, update, delete, read) has a different set of security rules. However, with the current implementation of the deserializer (in which we are using the Doctrine object constructor), the user can issue a create request, but specify an "id" as part of the payload. The Doctrine object constructor will then return a mapped entity before deserialization begins, allowing the end user to perform an update (while the server still thinks it's doing a create).

Also, on this point:
I was considering making a separate object constructor - but I need to give some attributes to the object constructor on each use (such as the ID which it should construct an object for). Right now, the only way to get those attributes to the deserializer is to include them in the payload string that gets passed to it - which is precisely what I'd like to avoid.

There are ways to handle this in the actual REST endpoint, but none of them are really ideal.What I'd like to be able to do is pass an already-constructed object (which my REST endpoint will handle fetching) to the deserializer and just have it do it's property mapping onto the object. This way, I can always pass a blank object in create calls, while I can pass a constructed object in update calls.

Would this be possible? I could submit a PR if this is something you'd be willing to implement.

**Comment by terwey** [comment]
I followed @eschwartz recommendation and just did a

```bash
cp vendor/jms/serializer/tests/JMS/Serializer/Tests/Fixtures/InitializedObjectConstructor.php src/myApp/
```
Modified the namespace in the ```InitializedObjectConstructor.php``` and it all works like a charm after this.

Can this class be moved into a more proper and permanent location so I don't have to maintain it myself?

**Comment by RedEdgeKatelyn** [comment]
For anyone trying to do this in Symfony, I copied `vendor/jms/serializer/tests/JMS/Serializer/Tests/Fixtures/InitializedObjectConstructor.php` to a Services folder in my Bundle and added this to config.yml:

    services:
        jms_serializer.object_constructor:
            alias: jms_serializer.initialized_object_constructor
            public: false
        jms_serializer.initialized_object_constructor:
             class:        VendorName\Bundle\ApiBundle\Services\InitializedObjectConstructor
             arguments:    ["@jms_serializer.doctrine_object_constructor"]

**Comment by faheemhameed** [comment]
Note about the Symfony helped a lot. Thanks!

**Comment by tom10271** [comment]
@RedEdgeKatelyn I am not sure code changed or not but your code snippet is not work.

Here is the workable version:

```
    jms_serializer.object_constructor:
        alias: jms_serializer.initialized_object_constructor
        public: false

    jms_serializer.initialized_object_constructor:
         class:        Acme\YourBundle\Serializer\InitializedObjectConstructor
         arguments:    ["@jms_serializer.unserialize_object_constructor"] 
```

**Comment by bendbennett** [comment]
Thanks @RedEdgeKatelyn and @tom10271 as a Symfony user your solution worked for me. But I couldn't help but feel that this should be soluble through configuration. 
[](url)
Stumbled across a [SO](http://stackoverflow.com/questions/16525849/how-to-update-symfony2-doctrine-entity-from-a-groups-inclusion-policy-jmsserial) post and followed the suggested configuration change (in app/config/services.yml):
````
services:
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
```` 

This worked for me when I then used JMS serializer:
```php
$this->serializer->deserialize($request->getContent(), 'MyApp\Entity\User', 'json');
```
Only thing to watch out for is that the **id** of the object must appear in the body of the request, otherwise instead of updating a pre-hydrated instance of User, a new instance of User will be created.

Can also confirm that the additional changes suggested in the [SO](http://stackoverflow.com/questions/16525849/how-to-update-symfony2-doctrine-entity-from-a-groups-inclusion-policy-jmsserial) post suggested for Mongo also work:
````
services:
    jms_serializer.doctrine_object_constructor:
        class:        %jms_serializer.doctrine_object_constructor.class%
        public:       false
        arguments:    ["@doctrine_mongodb", "@jms_serializer.unserialize_object_constructor"]

    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
````

Kudos to [Heyflynn](http://stackoverflow.com/users/1273153/heyflynn) and [con](http://stackoverflow.com/users/729991/con)

Works with PHP 7 too :)

**Comment by goetas** [comment]
[ObjectConstructorInterface](https://github.com/schmittjoh/serializer/blob/bb51b6396ae4512f09a36f1ca27155fef21b3aca/src/JMS/Serializer/Construction/ObjectConstructorInterface.php) has been updated and is possible to get objects from the context attributes

**Comment by karousn** [comment]
@goetas : if possible to have an example of implementation for that, i looking to use context attributes but until now **$context->attributes->all()**  have an empty array, i don't know how can i set my object there.

**Comment by goetas** [comment]
@karousn you can have a look at it on https://github.com/schmittjoh/serializer/blob/ec09e10524d371f40f095dd801eb374fa0d11a56/tests/Serializer/BaseSerializationTest.php#L714

**Comment by yakobabada** [comment]
@goetas I still confused. Could you provide with an example for Symfony 4.2, please?

**Comment by philippeamar** [comment]
@goetas Could you provide with an example for Symfony 5 please?

**Comment by nnmer** [comment]
https://stackoverflow.com/a/56128315/3419751
https://jmsyst.com/libs/serializer/master/cookbook/object_constructor#deserialize-on-existing-objects

@yakobabada  this does work for my SF 4.4

@philippeamar 
I guess it may still work for SF 5

**Comment by jeandonaldroselin** [comment]
@philippeamar, all

**In short** : I have a simple working snippet to deserialize an object into another in Symfony 6 🙂 !!
You can go to Snippet part directly or read the long version, it's up to you ;).

**In long** : I was reading this [Open Classrooms great course](https://openclassrooms.com/fr/courses/7709361-construisez-une-api-rest-avec-symfony/7795161-rendez-votre-api-autodecouvrable#/id/r-7795167) to learn how to create an API with latest Symfony (6).

During the course we needed to replace the Symfony native Serializer by JMS/Serializer in order to make Hateos
(autodiscovery) component work properly. So we replaced the native Symfony serializer but with no concrete solution to deserialize an object in another when performing an entity update.

The solution given in the course was to assign manually each attribute of the updated object to the existing objet.
So I did it to go ahead in the course. But now I have finished the course, I cannot use the course advice in real life for updating objets. (it is not at all optimized)

After testing many solutions, I found this which is working and I use it in real life, enjoy 🙂 !!

**Snippet**

- Step 1 : Create a App\Service\InitializedObjectConstructor class

```php 
<?php

namespace App\Service;

use JMS\Serializer\Construction\ObjectConstructorInterface;
use JMS\Serializer\DeserializationContext;
use JMS\Serializer\Metadata\ClassMetadata;
use JMS\Serializer\Visitor\DeserializationVisitorInterface;

class InitializedObjectConstructor implements ObjectConstructorInterface
{
    private $fallbackConstructor;

    /**
     * @param ObjectConstructorInterface $fallbackConstructorClassName Fallback object constructor
     */
    public function __construct($fallbackConstructorClassName)
    {
        $this->fallbackConstructor = new $fallbackConstructorClassName();
    }

    /**
     * {@inheritdoc}
     */
    public function construct(
        DeserializationVisitorInterface $visitor,
        ClassMetadata $metadata,
        $data,
        array $type,
        DeserializationContext $context
    ): ?object {
        if ($context->hasAttribute('target') && 1 === $context->getDepth()) {
            return $context->getAttribute('target');
        }

        return $this->fallbackConstructor->construct($visitor, $metadata, $data, $type, $context);
    }
}
```

- Step 2 : Declare the class as service for object construction in config/services.yaml


```yaml
services:
    ...
    jms_serializer.object_constructor:
        class: App\Service\InitializedObjectConstructor
        arguments: ['\JMS\Serializer\Construction\UnserializeObjectConstructor']
```


- Step 3 : Use it in your controller or service


```php
    #[Route('/api/todos/{id}', name: 'updateOneTodo', methods: 'PUT')]
    #[IsGranted('ROLE_ADMIN', message: "You has no sufficient rights to perform this operation")]
    public function updateOne(Request $request,
                              SerializerInterface $serializer,
                              Todo $todo,
                              EntityManagerInterface $em): JsonResponse
    {
        $context = new DeserializationContext();
        $context->setAttribute('target', $todo);
        $updatedTodo = $serializer->deserialize($request->getContent(), Todo::class, 'json', $context);
        $em->persist($updatedTodo);
        $em->flush();
        return new JsonResponse($serializer->serialize($updatedTodo, 'json'), JsonResponse::HTTP_OK, [], true);
    }
```
