### ISSUE TITLE
Add description to PropertyMetadata?

### ISSUE THREAD

**Issue by sandermarechal** [schmittjoh/serializer#800]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Would it be a good idea to add a `description` field to the `PropertyMetadata`? There are many libraries that can use the serializer metadata for various purposes. For example, Symfony's PropertyInfo component (which IIRC is used by the form component) and various API tools such as NelmioApiDoc.

In my case, I am generating Swagger documentation from the JMS Serializer metadata using the NelmioApiDoc bundle. My serializer configuration is in XML. Properties in Swagger should have a description. For regular properties I can simply read the DocBlock for the description. For virtual properties I can look at the `@return` documentation on the getter. But there is no way to figure out the description for an expression property.

JMS Serializer is often used for APIs, and API documentation is often generated from the JMS metadata. Does it make sense to include a `description` field on properties (and maybe even on classes) for such uses?

Or is there another (better) way to add extra data to the serializer configuration in such a way that I can later retrieve it?

**Comment by goetas** [comment]
More than JMS serializer, this is a feature that `NelmioApiDoc` or similar tools should offer. 

"description" has nothing to do with "serialization".

As example:

```php

class User
{
 /** 
 * @API\Description("bla bla") 
 * @Serializer\Type("string") 
 */
  protected $name;
}
```

api-specific bundles can extract the `@API\Description` annotation and place it where necessary.

**Comment by sandermarechal** [comment]
The serialization configuration describes the data model of the API. And in the case of expression properties there is nothing to add a description to. Especially if you use XML or Yaml instead of annotations for the serialization configuration.

I thought it odd to define a (virtual expression) field in my XML file, but then have to place the description of that field in some totally unrelated place.

**Comment by sandermarechal** [comment]
Here is an example of my serialization config. Where do you suggest I add the documentation for the "imageUrl" field?

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<serializer>
    <class name="App\Entity\User" xml-root-name="User" exclusion-policy="all" access-type="public_method">
        <property name="username" type="string" expose="true" />
        <virtual-property
            name="imageUrl"
            type="string"
            expose="true"
            expression="service('router')->generate('app_user_image', {'id' => object.getImage().getId()}, 1)"
        />
    </class>
</serializer>

**Comment by goetas** [comment]
You probably have to implement something similar to it, but extracting data not from the jms-metadata, but from apidoc specific metadata files.

If you want to use annotations, the job is pretty easy. the doctrine annotation reader does most of the job for you. if you want to allow more formats as xml or yml, things get a bit more "boring" because you have to implement a "metadata" reader, and later the produced metadata needs to be loaded into nelmio api doc...

Essentially:
1) you need to implement a metadata reader. a great example is https://github.com/willdurand/Hateoas/tree/master/src/Hateoas/Configuration/Metadata
2) load the generated metadata into nelmio using something very similar to [JMSModelDescriber](https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/JMSModelDescriber.php)

**Comment by sandermarechal** [comment]
Thanks
