### ISSUE TITLE
Default serialization in custom handler returns "null"

### ISSUE THREAD

**Issue by egonolieux** [schmittjoh/serializer#889]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I have a custom handler `Type("Entity<EntityClass, 'field'>")` to serialize and deserialize entities. The _field_ parameter is optional and is used to serialize/deserialize to/from a certain entity field such as _id_ or _name_. When no _field_ parameter is given, I want the custom handler to perform the default serialization process; only custom deserialization is required if no _field_ parameter is given.

To implement this, I used the code mentioned in this issue: https://github.com/schmittjoh/serializer/pull/620#issuecomment-239135752:

```
public function serialize(VisitorInterface $visitor, $data, array $type, Context $context)
{
    // ...
    $type['name'] = get_class($data);
    return $visitor->getNavigator()->accept($data, $type, $context);
    // ...
}
```

The custom handler is defined on the entity field like this:

```
/**
 * @ORM\ManyToOne(
 *     targetEntity="AppBundle\Entity\Expansion",
 *     inversedBy="cards",
 *     cascade="merge"
 * )
 * @ORM\JoinColumn(name="expansion_id", referencedColumnName="id")
 * 
 * @Serializer\Type("Entity<AppBundle\Entity\Expansion>")
 */
private $expansion;
```
However, the `accept` method always seems to return `null`. Am I doing something wrong? Is this a bug?

**Comment by goetas** [comment]
looking at the code, it should work. of course it depends how your custom handler is implemented, if is json or xml... and many other variables.

if you are able to isolate the problem in a separate test repo i can try to help, but the info provided for now are not enough.

**Comment by egonolieux** [comment]
Thanks for your answer, I'll try to isolate the problem in a test asap.

**Comment by egonolieux** [comment]
I isolated the problem in the following test: [jms-serializer-test.zip](https://github.com/schmittjoh/serializer/files/1807142/jms-serializer-test.zip).

By the way, is there a formal/recommended way of submitting tests? I have no previous experience in providing tests in this repository/GitHub.

**Comment by egonolieux** [comment]
Any news on this?

**Comment by goetas** [comment]
The problem is in this part of code:

```php
class EntityHandler implements SubscribingHandlerInterface
{
    ......
    public function serialize(VisitorInterface $visitor, $data, array $type, Context $context)
    {
        $entityField = $this->getEntityField($type);
        // If the entity field is not set, resume default serialization.
        if ($entityField === null) {
            $type['name'] = get_class($data);
            return $visitor->getNavigator()->accept($data, $type, $context);
        }
```

If `$entityField` is null, you are asking to the serializer to handle the object serialization even if the serialization of `$data` is already in progress and `EntityHandler` declared to be responsible for it. 
The graph navigator is already visiting the `$data` object and  `EntityHandler` is responsible for it and can not "change its mind" as ask the serializer to continue instead of it.

[Here](https://github.com/schmittjoh/serializer/blob/78e7df461c0030ff7cedd0b934e828efbcf852a7/src/JMS/Serializer/GraphNavigator.php#L167) is the reason of the null return.

In this case you have to decide to handle the serialization inside your handler or to not use the virtual type for this object.


https://github.com/schmittjoh/serializer/issues/446 is a feature request for your usecase.


> By the way, is there a formal/recommended way of submitting tests? I have no previous experience in providing tests in this repository/GitHub.

The test case you provided, was just perfect. Instead of a ZIP file was better to setup a simple public repo on Github and run a build on TravisCI. (I could comment your code directly there instead of doing copy/paste here...) But anyway the test case was very good.
