### ISSUE TITLE
obsolete strategies when calling Context::setVersion/setGroups more than once

### ISSUE THREAD

**Issue by sepetrov** [schmittjoh/serializer#98]
Hi,

First, I'd like to thank you for the great library.

Using it I stumbled on a situation which caused unexpected result.
Every time when you set the version ([Context::setVersion](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L149)) or the groups ([Context::setGroups](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L164)) of the context, the context adds new [VersionExclusionStrategy](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L156) and [GroupsExclusionStrategy](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L171) respectively. As result changing the version or the groups will correctly update the attributes `version` and `groups`, but it will also add new exclusion strategies with the new value(s) without removing the obsolete exclusion strategies. In my opinion this is unexpected and the context should either remove the old exclusion strategies or not attempt to update the [DisjunctExclusionStrategy](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L122) ([here](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L156) and [here](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Context.php#L171)).

Cheers!

**Comment by scaytrase** [comment]
@goetas I'm reaching here to argument for making this possible to have some kind of mutating methods (like `addGroups`) while leaving `setGroups` fully replacing the old ones.

Since we can configure context globally with [symfony bundle configuration](https://github.com/schmittjoh/JMSSerializerBundle/blob/master/DependencyInjection/Configuration.php#L321) it would be nice to be able to mutate it, not replace when calling `addGroups` on the obtained context from bundle factory

**Comment by goetas** [comment]
@scaytrase  There are many advanteages on having the context "not-mutable".

What about adding a `MutableDisjunctExclusionStrategy` class? the `DisjunctExclusionStrategy` will still be the default, but having `MutableDisjunctExclusionStrategy` will allow to add this new behavior, while staying compatible with the current way of setting groups

**Comment by scaytrase** [comment]
@goetas there is not problem having context immutable, just give us a possibility not to override, but merge groups in some way.

Btw. context is already mutable, since it has `setGroups` method, but there is no option to obtain already configured groups from it, like `$context->setGroups(array_merge($context->getGroups, $myGroups))`
